// This file was generated by Slice Machine. You may edit this file.

import * as React from 'react'
import { graphql } from 'gatsby'

// TODO: Implement the {{componentName}}Slice component.
//
// → Learn how to render this component with <SliceZone>
//   https://prismic.io/docs/technologies/template-slices-gatsby
export default function {{componentName}}Slice({ slice }) {
  return (
    <section>
      Placeholder {{componentName}} ({slice.variation}) component
    </section>
  )
}

// TODO: Create a GraphQL fragment for each Slice variant.
//
// → Learn how to query for fields
//   https://prismic.io/docs/technologies/retrieve-fields-and-slices-gatsby
//
// → Learn how to use this GraphQL fragment
//   https://prismic.io/docs/technologies/fragments-gatsby
export const fragment = graphql`
  fragment Prismic{{componentName}} on Prismic{{componentName}} {
    # Fields for the DefaultSlice variation
    ... on Prismic{{componentName}}DefaultSlice {
      # Add your fields here (__typename can be removed)
      __typename
    }

    # Required fields for the SliceZone component
    ... on PrismicSharedSliceType {
      slice_type
      variation
    }
  }
`
