// This file was generated by Slice Machine. You may edit this file.

import * as React from 'react'
import { graphql } from 'gatsby'

// TODO: Implement the {{componentName}}Slice component.
//
// → Learn how to render this component with <SliceZone>
//   https://prismic.io/docs/technologies/template-slices-gatsby
export default function {{componentName}}Slice({ slice }) {
  return (
    <section>
      Placeholder {{componentName}} component
    </section>
  )
}

// TODO: Create a GraphQL fragment for each Slice variant.
//
// → Learn how to query for fields
//   https://prismic.io/docs/technologies/retrieve-fields-and-slices-gatsby
//
// → Learn how to use this GraphQL fragment
//   https://prismic.io/docs/technologies/fragments-gatsby
export const fragment = graphql`
  fragment Prismic{{componentName}}DefaultSlice on Prismic{{componentName}}DefaultSlice {
    slice_type
    # Add your fields here
  }
`
