
name: Setup Node LTS
description: Setup Node LTS
runs:
  using: composite
  steps:
    - name: Use Node.js LTS
      uses: actions/setup-node@v3
      with:
        cache: yarn
        node-version: lts/*
        registry-url: https://registry.npmjs.org
