
name: 'Setup Node 16'
description: 'Setup Node 16'
runs:
  using: 'composite'
  steps:
    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: "npm"