defaultSemverRangePrefix: ""
enableScripts: false
enableTelemetry: false
initFields:
  license: Apache-2.0
  version: 0.0.0
initScope: slicemachine
nodeLinker: node-modules
npmPublishRegistry: https://registry.npmjs.org
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
supportedArchitectures:
  cpu:
    - arm64
    - x64
  libc:
    - glibc
  os:
    - darwin
    - linux
    - win32
yarnPath: .yarn/releases/yarn-3.6.0.cjs
