export enum ModalKeysEnum {
  LOGIN = "LOGIN",
  CREATE_CUSTOM_TYPE = "CREATE_CUSTOM_TYPE",
  RENAME_SLICE = "RENAME_SLICE",
  RENAME_VARIATION = "RENAME_VARIATION",
  SCREENSHOT_PREVIEW = "SCREENSHOT_PREVIEW",
  SCREENSHOTS = "SCREENSHOTS",
  DELETE_SLICE = "DELETE_SLICE",
  DELETE_VARIATION = "DELETE_VARIATION",
  SOFT_DELETE_DOCUMENTS_DRAWER = "SOFT_DELETE_DOCUMENTS_DRAWER",
  HARD_DELETE_DOCUMENTS_DRAWER = "HARD_DELETE_DOCUMENTS_DRAWER",
  REFERENCES_MISSING_DRAWER = "REFERENCES_MISSING_DRAWER",
  SIMULATOR_SETUP = "SIMULATOR_SETUP",
}

export type ModalStoreType = Record<ModalKeysEnum, boolean>;
