export enum ModalKeysEnum {
  LOGIN = "LOGIN",
  RENAME_SLICE = "RENAME_SLICE",
  SCREENSHOT_PREVIEW = "SCREENSHOT_PREVIEW",
  SCREENSHOTS = "SCREENSHOTS",
  DELETE_SLICE = "DELETE_SLICE",
  SIMULATOR_SETUP = "SIMULATOR_SETUP",
}

export type ModalStoreType = Record<ModalKeysEnum, boolean>;
