// This file is generated by Slice Machine. Update with care!

import BlogSectionThreeColumnCards from './BlogSectionThreeColumnCards';
import ContactSectionSplitTwoTone from './ContactSectionSplitTwoTone';
import ContentSectionCentered from './ContentSectionCentered';
import ContentSectionCenteredEmbed from './ContentSectionCenteredEmbed';
import ContentSectionCenteredImage from './ContentSectionCenteredImage';
import ContentSectionTwoColumnsWithImage from './ContentSectionTwoColumnsWithImage';
import FeaturedSectionCentered22 from './FeaturedSectionCentered22';
import HeaderSectionSimpleCentered from './HeaderSectionSimpleCentered';
import HeroSectionSplit from './HeroSectionSplit';
import Separator from './Separator';
import StatsSectionSplitWithImage from './StatsSectionSplitWithImage';

export {
	BlogSectionThreeColumnCards,
	ContactSectionSplitTwoTone,
	ContentSectionCentered,
	ContentSectionCenteredEmbed,
	ContentSectionCenteredImage,
	ContentSectionTwoColumnsWithImage,
	FeaturedSectionCentered22,
	HeaderSectionSimpleCentered,
	HeroSectionSplit,
	Separator,
	StatsSectionSplitWithImage,
};

export const components = {
	blog_section_three_column_cards: BlogSectionThreeColumnCards,
	contact_section_split_two_tone: ContactSectionSplitTwoTone,
	content_section_centered: ContentSectionCentered,
	content_section_centered_embed: ContentSectionCenteredEmbed,
	content_section_centered_image: ContentSectionCenteredImage,
	content_section_two_columns_with_image: ContentSectionTwoColumnsWithImage,
	featured_section_centered22: FeaturedSectionCentered22,
	header_section_simple_centered: HeaderSectionSimpleCentered,
	hero_section_split: HeroSectionSplit,
	separator: Separator,
	stats_section_split_with_image: StatsSectionSplitWithImage,
};
