// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  call_to_action: dynamic(() => import("./CallToAction")),
  category_preview_with_image_backgrounds: dynamic(() =>
    import("./CategoryPreviewWithImageBackgrounds")
  ),
  category_preview_with_scrolling_cards: dynamic(() =>
    import("./CategoryPreviewWithScrollingCards")
  ),
  chart_slice: dynamic(() => import("./ChartSlice")),
  external_video_slice: dynamic(() => import("./ExternalVideoSlice")),
  hero_banner: dynamic(() => import("./HeroBanner")),
  product_features_with_wide_images: dynamic(() =>
    import("./ProductFeaturesWithWideImages")
  ),
  product_list_with_cta: dynamic(() => import("./ProductListWithCta")),
  product_overview_with_image_grid: dynamic(() =>
    import("./ProductOverviewWithImageGrid")
  ),
  promo_section_fading_background_testimonials: dynamic(() =>
    import("./PromoSectionFadingBackgroundTestimonials")
  ),
  promo_section_full_width_with_overlapping_image_tiles: dynamic(() =>
    import("./PromoSectionFullWidthWithOverlappingImageTiles")
  ),
  promo_section_image_tiles: dynamic(() => import("./PromoSectionImageTiles")),
  promo_section_with_background_image: dynamic(() =>
    import("./PromoSectionWithBackgroundImage")
  ),
};
