// This file is generated by Slice Machine. Update with care!

import CategoryPreviewWithImageBackgrounds from './CategoryPreviewWithImageBackgrounds';
import CategoryPreviewWithScrollingCards from './CategoryPreviewWithScrollingCards';
import ChartSlice from './ChartSlice';
import ExternalVideoSlice from './ExternalVideoSlice';
import HeroBanner from './HeroBanner';
import ProductFeaturesWithWideImages from './ProductFeaturesWithWideImages';
import ProductListWithCta from './ProductListWithCta';
import ProductOverviewWithImageGrid from './ProductOverviewWithImageGrid';
import PromoSectionFadingBackgroundTestimonials from './PromoSectionFadingBackgroundTestimonials';
import PromoSectionFullWidthWithOverlappingImageTiles from './PromoSectionFullWidthWithOverlappingImageTiles';
import PromoSectionImageTiles from './PromoSectionImageTiles';
import PromoSectionWithBackgroundImage from './PromoSectionWithBackgroundImage';

export {
	CategoryPreviewWithImageBackgrounds,
	CategoryPreviewWithScrollingCards,
	ChartSlice,
	ExternalVideoSlice,
	HeroBanner,
	ProductFeaturesWithWideImages,
	ProductListWithCta,
	ProductOverviewWithImageGrid,
	PromoSectionFadingBackgroundTestimonials,
	PromoSectionFullWidthWithOverlappingImageTiles,
	PromoSectionImageTiles,
	PromoSectionWithBackgroundImage,
};

export const components = {
	category_preview_with_image_backgrounds: CategoryPreviewWithImageBackgrounds,
	category_preview_with_scrolling_cards: CategoryPreviewWithScrollingCards,
	chart_slice: ChartSlice,
	external_video_slice: ExternalVideoSlice,
	hero_banner: HeroBanner,
	product_features_with_wide_images: ProductFeaturesWithWideImages,
	product_list_with_cta: ProductListWithCta,
	product_overview_with_image_grid: ProductOverviewWithImageGrid,
	promo_section_fading_background_testimonials: PromoSectionFadingBackgroundTestimonials,
	promo_section_full_width_with_overlapping_image_tiles: PromoSectionFullWidthWithOverlappingImageTiles,
	promo_section_image_tiles: PromoSectionImageTiles,
	promo_section_with_background_image: PromoSectionWithBackgroundImage,
};
