export type LoadingStoreType = Record<LoadingKeysEnum, boolean>;

export enum LoadingKeysEnum {
  LOGIN = "LOGIN",
  REVIEW = "REVIEW",
  CHECK_SIMULATOR = "CHECK_SIMULATOR",
  CREATE_CUSTOM_TYPE = "CREATE_CUSTOM_TYPE",
  RENAME_CUSTOM_TYPE = "RENAME_CUSTOM_TYPE",
  SAVE_CUSTOM_TYPE = "SAVE_CUSTOM_TYPE",
  PUSH_CUSTOM_TYPE = "PUSH_CUSTOM_TYPE",
  CREATE_SLICE = "CREATE_SLICE",
  RENAME_SLICE = "RENAME_SLICE",
  GENERATE_SLICE_SCREENSHOT = "GENERATE_SLICE_SCREENSHOT",
  GENERATE_SLICE_CUSTOM_SCREENSHOT = "GENERATE_SLICE_CUSTOM_SCREENSHOT",
  SAVE_SLICE = "SAVE_SLICE",
  PUSH_SLICE = "PUSH_SLICE",
  CHANGES_PUSH = "CHANGES_PUSH",
  CHANGELOG = "CHANGELOG",
}
