export type LoadingStoreType = Record<LoadingKeysEnum, boolean>;

export enum LoadingKeysEnum {
  LOGIN = "LOGIN",
  REVIEW = "REVIEW",
  CHECK_SIMULATOR = "CHECK_SIMULATOR",
  CHECK_SIMULATOR_IFRAME = "CHECK_SIMULATOR_IFRAME",
  RENAME_SLICE = "RENAME_SLICE",
  GENERATE_SLICE_CUSTOM_SCREENSHOT = "GENERATE_SLICE_CUSTOM_SCREENSHOT",
  DELETE_SLICE = "DELETE_SLICE",
  SIMULATOR_SAVE_MOCK = "SIMULATOR_SAVE_MOCK",
  CHANGELOG = "CHANGELOG",
}
