import { Text } from "@prismicio/editor-ui";

import type {
  OnboardingStep,
  OnboardingStepContentDefinition,
  OnboardingStepType,
} from "@/features/onboarding/types";

export const onboardingSteps: OnboardingStep[] = [
  {
    id: "createPageType",
    title: "Create a Page Type",
    description: "Build the structure for your page.",
  },
  {
    id: "codePage",
    title: "Code Your Page Type",
    description: "Prepare your code to fetch content.",
  },
  {
    id: "createSlice",
    title: "Create a Slice",
    description: "Build a reusable website section.",
  },
  {
    id: "reviewAndPush",
    title: "Review and Push Changes",
    description: "Enable editors to create content.",
  },
  {
    id: "createContent",
    title: "Create Content in the Page Builder",
    description: "Publish a page to the Prismic API.",
  },
  {
    id: "renderPage",
    title: "Render your page",
    description: "View your page in the browser.",
  },
];

// TODO: Type check with satisfies once we upgrade to next > 12 to have at least the same number of steps
export const stepIndexNumeral = [
  "one",
  "two",
  "three",
  "four",
  "five",
  "six",
];

export const onboardingStepContent: Record<
  OnboardingStepType,
  OnboardingStepContentDefinition
> = {
  createPageType: {
    videoUrl:
      "https://res.cloudinary.com/dmtf1daqp/video/upload/v1700213517/IN-APP-GUIDE-SM/ADD_SLICE.mp4",
    content: () => (
      <Text>
        A page type is a base content structure editors will use to create pages
        in the Page Builder (Prismic's content creation UI). A page type can be
        reusable (e.g., for multiple blog posts) or single (e.g., for a one-time
        page like the homepage).
      </Text>
    ),
  },
  codePage: {
    videoUrl:
      "https://res.cloudinary.com/dmtf1daqp/video/upload/v1700213517/IN-APP-GUIDE-SM/CODE_SNIP.mp4",
    content: () => (
      <Text>Prepare your code to query the content from the Prismic API.</Text>
    ),
  },
  createSlice: {
    videoUrl:
      "https://res.cloudinary.com/dmtf1daqp/video/upload/v1700213517/IN-APP-GUIDE-SM/ADD_SLICE.mp4",
    content: () => (
      <Text>
        Slices are website sections that can be reused on different pages with
        different content. Each slice has a code component automatically
        generated by Slice Machine. Start with a template and look at your code
        to see how it's structured.
      </Text>
    ),
  },
  reviewAndPush: {
    videoUrl:
      "https://res.cloudinary.com/dmtf1daqp/video/upload/v1700213517/IN-APP-GUIDE-SM/PUSH.mp4",
    content: () => (
      <Text>
        Your page types and slices currently exist only in your local project.
        Push them to your repository to make them available for your content
        editors.
      </Text>
    ),
  },
  createContent: {
    videoUrl:
      "https://res.cloudinary.com/dmtf1daqp/video/upload/v1700213517/IN-APP-GUIDE-SM/WRITE.mp4",
    content: () => (
      <Text>
        In Prismic, content creation takes place in the Prismic Page Builder UI.
        Open the Page Builder and start creating your first page.
      </Text>
    ),
  },
  renderPage: {
    videoUrl:
      "https://res.cloudinary.com/dmtf1daqp/video/upload/v1700213517/IN-APP-GUIDE-SM/PREVIEW.mp4",
    content: () => (
      <Text>
        Now that your content is published, you can run your project in your
        terminal and visit the page on your local server (e.g.,{" "}
        <Text component="code">localhost:3000/example-page</Text>). Your content
        should now be visible!
      </Text>
    ),
  },
};
