import type { SliceMachineManager } from "@slicemachine/manager";
import {
  generateTypes as generateTypesFromCodegen,
  detectTypesProvider,
} from "prismic-ts-codegen";
import { writeFile, mkdir } from "node:fs/promises";
import { dirname, join } from "node:path";
import chalk from "chalk";

const NON_EDITABLE_FILE_BANNER = `// Code generated by Slice Machine. DO NOT EDIT.`;

export interface GenerateTypesOptions {
  manager: SliceMachineManager;
  outputPath: string;
  verbose: boolean;
}

export async function generateTypes(
  options: GenerateTypesOptions,
): Promise<void> {
  const { manager, outputPath, verbose } = options;

  if (verbose) {
    console.log(chalk.gray("📡 Fetching remote custom types..."));
  }

  // Fetch remote models from Prismic API
  const customTypes = await manager.customTypes.fetchRemoteCustomTypes();

  if (verbose) {
    console.log(chalk.gray(`✅ Found ${customTypes.length} custom type(s)`));
    console.log(chalk.gray("📡 Fetching remote slices..."));
  }

  const slices = await manager.slices.fetchRemoteSlices();

  if (verbose) {
    console.log(chalk.gray(`✅ Found ${slices.length} slice(s)`));
    console.log(chalk.gray("🔧 Generating TypeScript types..."));
  }

  // Generate TypeScript types using prismic-ts-codegen
  let contents = generateTypesFromCodegen({
    customTypeModels: customTypes,
    sharedSliceModels: slices,
    clientIntegration: {
      includeCreateClientInterface: true,
      includeContentNamespace: true,
    },
    typesProvider: await detectTypesProvider({ cwd: process.cwd() }),
  });

  // Add non-editable banner
  contents = `${NON_EDITABLE_FILE_BANNER}\n\n${contents}`;

  // Write to file
  const fullPath = join(process.cwd(), outputPath);
  await mkdir(dirname(fullPath), { recursive: true });
  await writeFile(fullPath, contents, "utf8");

  if (verbose) {
    console.log(chalk.green(`✅ Types generated successfully!`));
    console.log(chalk.gray(`📄 Output: ${fullPath}`));
  }
}
