export const SCRIPT_NAME = "slicemachine";
export const SCRIPT_VALUE = "start-slicemachine";
export const INIT_COMMAND = "npx sm init";
export const SM_PACKAGE_NAME = "slice-machine-ui";
export const PRISMIC_REACT_PACKAGE_NAME = "prismic-reactjs";
export const PRISMIC_DOM_PACKAGE_NAME = "prismic-dom";
export const MANIFEST_FILE_NAME = "sm.json";
export const DEFAULT_SERVER_PORT = 5555;
export const DEFAULT_BASE = "https://prismic.io";
