export { installRequiredDependencies } from "./install-required-dependencies";
export { validatePkg } from "./validate-pkg";
export { chooseOrCreateARepository } from "./choose-or-create-a-repository";
export { detectFramework } from "./detect-framework";
export { loginOrBypass } from "./loginOrBypass";
export { configureProject } from "./configure-project";
export { displayFinalMessage } from "./display-final-message";
export { installLib } from "./install-lib";
export { sendStarterData } from "./sendStarterData";
