name: Cache node_modules
description: Cache node_modules
runs:
  using: composite
  steps:
    - name: Cache node_modules
      id: cache-dependencies
      uses: actions/cache@v4
      with:
        path: |
          node_modules
          */node_modules
          */*/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-dependencies
