name: Cache node_modules and artifacts
description: Cache node_modules and artifacts
runs:
  using: composite
  steps:
    - name: Cache node_modules
      id: cache-dependencies
      uses: actions/cache@v3
      with:
        path: |
          node_modules
          */*/node_modules
          ~/.cache/Cypress
          ~/.cache/ms-playwright
        key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-dependencies
    - name: Cache artifacts
      id: cache-artifacts
      uses: actions/cache@v3
      with:
        path: |
          packages/*/dist
          packages/core/build
        key: ${{ runner.os }}-${{ github.run_id }}-artifacts
