// This file is generated by Slice Machine. Update with care!

import AllFields from './AllFields';
import CallToAction from './CallToAction';
import CallToAction2 from './CallToAction2';
import CallToAction3 from './CallToAction3';
import MyAwesomeSlice from './MyAwesomeSlice';
import MyAwesomeZ from './MyAwesomeZ';
import MyNewSlice from './MyNewSlice';
import StrcututedTexts from './StrcututedTexts';
import WithMocks from './WithMocks';

export {
	AllFields,
	CallToAction,
	CallToAction2,
	CallToAction3,
	MyAwesomeSlice,
	MyAwesomeZ,
	MyNewSlice,
	StrcututedTexts,
	WithMocks,
};

export const components = {
	all_fields: AllFields,
	call_to_action: CallToAction,
	call_to_action2: CallToAction2,
	call_to_action3: CallToAction3,
	my_awesome_slice: MyAwesomeSlice,
	my_awesome_z: MyAwesomeZ,
	my_new_slice: MyNewSlice,
	strcututed_texts: StrcututedTexts,
	with_mocks: WithMocks,
};
