export { default as MySlice } from './MySlice'
export { default as AssA } from './AssA'
export { default as PascalA } from './PascalA'
export { default as PascalB } from './PascalB'
export { default as AsssA } from './AsssA'
export { default as MyCoolSlice } from './MyCoolSlice'
export { default as MyAwessomecom } from './MyAwessomecom'