// This file is generated by Prismic local builder. Update with care!

export { default as CallToAction } from './CallToAction'
export { default as CallToAction2 } from './CallToAction2'
export { default as CallToAction3 } from './CallToAction3'
export { default as MyAwesomeZ } from './MyAwesomeZ'
export { default as StrcututedTexts } from './StrcututedTexts'
export { default as WithMocks } from './WithMocks'
