/**
 * Banner text added to files that should not be edited by users.
 */
export const NON_EDITABLE_FILE_BANNER =
	"// Code generated by Slice Machine. DO NOT EDIT.";

export const MODEL_FILENAME = "model.json";

export const TSCONFIG_FILENAME = "tsconfig.json";
